project_id = "xppgoccktxwfpqqvcqug"

[functions.chat]
verify_jwt = true

[functions.generate-campaign]
verify_jwt = true

[functions.scrape-moblix]
verify_jwt = false

[functions.public-chat]
verify_jwt = false

[functions.perplexity-chat]
verify_jwt = true